### ISSUE TITLE
Licence file

### ISSUE THREAD

**Issue by linux-lukas** [tuxedocomputers/tuxedo-systeminfos#12]
Is it intentional that there is no licence file in the repository?

My question would be to what extent this script could be used for e.g. non-profit organisations and their IT organisation?

**Comment by vinzv** [comment]
Hi... that wasn't intentionally, indeed. Fixed now via https://github.com/tuxedocomputers/tuxedo-systeminfos/commit/b2746d1e13f54d5f0155df060ee4ce80a040ad63

Thanks for pointing out!
