### ISSUE TITLE
add efibootmgr to install required dependencies.

### ISSUE THREAD

**Issue by git001** [tuxedocomputers/tuxedo-systeminfos#14]
I have run today the systeminfos.sh and there was one command not found `efibootmgr`.

After running the install command was the command found.

```shell
apt install efibootmgr
```

it looks to me that the `efibootmgr`  is missed in this line.
https://github.com/tuxedocomputers/tuxedo-systeminfos/blob/master/systeminfos.sh#L97

**Comment by StevenSeifried** [comment]
Hi,
thank you for the hint, I fixed it with 935a5badf280d71503030e43468178c0f44b64a6
